CREATE TABLE [vc].[procurement_data] (
    [procurement_data_id]     INT             IDENTITY (1, 1) NOT NULL,
    [procurement_category_id] INT             NOT NULL,
    [function_id]             INT             NOT NULL,
    [business_unit_id]        INT             NOT NULL,
    [designation_id]          INT             NOT NULL,
    [year]                    INT             NULL,
    [year_id]                 INT             NOT NULL,
    [account_number]          NVARCHAR (100)  NOT NULL,
    [amount]                  NUMERIC (12, 2) NOT NULL,
    [is_direct]               BIT             NOT NULL,
    [spend_type_id]           INT             NOT NULL,
    [amount_local]            NUMERIC (12)    NULL,
    [department_id]           INT             NULL,
    [level_1_filter_id]       INT             NULL,
    [level_2_filter_id]       INT             NULL,
    [level_3_filter_id]       INT             NULL,
    [saving_source_id]        INT             NULL,
    [is_labor]                BIT             NULL,
    [cost_center_id]          INT             NULL,
    [account_description]     NVARCHAR (500)  NULL,
    CONSTRAINT [PK_procurement_data] PRIMARY KEY CLUSTERED ([procurement_data_id] ASC),
    CONSTRAINT [fk_procurement_data_01] FOREIGN KEY ([procurement_category_id]) REFERENCES [vc].[procurement_category] ([procurement_category_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_02] FOREIGN KEY ([function_id]) REFERENCES [vc].[function] ([function_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_03] FOREIGN KEY ([business_unit_id]) REFERENCES [vc].[business_unit] ([business_unit_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_04] FOREIGN KEY ([spend_type_id]) REFERENCES [vc].[spend_type] ([spend_type_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_05] FOREIGN KEY ([designation_id]) REFERENCES [vc].[designation] ([designation_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_07] FOREIGN KEY ([department_id]) REFERENCES [vc].[department] ([department_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_08] FOREIGN KEY ([level_1_filter_id]) REFERENCES [vc].[level_filter] ([level_filter_id]) ON DELETE CASCADE,
    CONSTRAINT [fk_procurement_data_09] FOREIGN KEY ([level_2_filter_id]) REFERENCES [vc].[level_filter] ([level_filter_id]),
    CONSTRAINT [fk_procurement_data_10] FOREIGN KEY ([level_3_filter_id]) REFERENCES [vc].[level_filter] ([level_filter_id]),
    CONSTRAINT [fk_procurement_data_11] FOREIGN KEY ([year_id]) REFERENCES [vc].[year] ([year_id]),
    CONSTRAINT [fk_procurement_data_12] FOREIGN KEY ([cost_center_id]) REFERENCES [vc].[cost_center] ([cost_center_id]),
    CONSTRAINT [fk_procurement_data_13] FOREIGN KEY ([saving_source_id]) REFERENCES [vc].[saving_source] ([saving_source_id])
);

